Testing `test/e2e/alcotest/failing/exception_in_test.ml'.
This run has ID `<uuid>'.

  [PASS]    test-a › Passing
> [FAIL]    test-a › Failing
  [PASS]    test-b › Another pass

┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]    test-a › Failing                                                   │
└──────────────────────────────────────────────────────────────────────────────┘
[exception] Dune__exe__Exception_in_test.Foo("message")
            <stacktrace>
            
Logs saved to `<build-context>/_build/_tests/<test-dir>/test-a/Failing.output'.
 ──────────────────────────────────────────────────────────────────────────────

Full test results in `<build-context>/_build/_tests/<test-dir>'.
1 failure! in <test-duration>s. 3 tests run.
